### ISSUE TITLE
scrollToEnd is fired when typeahead is present before reaching scroll end

### ISSUE THREAD

**Issue by neil-coutinho** [ng-select/ng-select#1018]
**Describe the bug**

If you have a typeahead present the scrollToEnd is fired even before you reach the bottom of the options.

**Reproducbile example**
[StackBlitz](https://stackblitz.com/edit/angular-ypybo3) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):

1. Open the dropdown (It loads with a set of options)

1. Scroll down to the 2nd option

1. Now type something in the search box, you will see that after the typeahead subject emits a value the scrollToEnd event is fired as well

**Expected behavior**
ScrollToEnd should only fire if the user has reached the end of the list. Not when the list is reset or updated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [Chrome]

**Comment by anjmao** [comment]
@neil-coutinho Thanks for a good catch. This happens because after you scrolled to to second item ng-select checks if last item is reached and as you later type in search and only few items are visible it fires that event. Probably the simplest fix would be to reset fire to end flag if items changed https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-dropdown-panel.component.ts#L122

**Comment by janstadt** [comment]
We're seeing that with this change we're not seeing the event being fired due to a rounding issue.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1872087/67428180-448bd580-f5a3-11e9-981f-c92769b5edb4.png)

Thoughts on rounding up here?

```
if (ceil(scrollTop + this._dropdown.clientHeight) >= padding.clientHeight) { ... }
```

**Comment by nrcdmovliaiko** [comment]
any updates?

**Comment by chzeeshansaleem** [comment]
i have faced this same issue how to solve it.
