### ISSUE TITLE
Keyboard navigation gains default focus

### ISSUE THREAD

**Issue by Goonersid** [ng-select/ng-select#103]
I have a requirement which varies slightly with the default behaviour of the component.. 

Requirement : Have the first item in a dropdown gain focus only when the user wants to focus by pressing the down arrow key on the input..

Currently on filtering , the first item gains focus by default..
Is it possible to introduce a default Focus flag which is true by default and can be turned to false if the above behaviour is intended??

**Comment by anjmao** [comment]
@Goonersid First item in dropdown gets focused because it indicates that if you press enter then first item will be selected. If we add this flag then we will need to prevent selecting first item on enter click so user should always use arrows navigation to select item. Also there are cases then you filter something and there is only item to select from, then you dont need to use keyboard arrows to select it because first item is always focused.

**Comment by varnastadeus** [comment]
I think we need to consider making it configurable.

**Comment by Goonersid** [comment]
@anjmao @varnastadeus Can i know the final decision on this??

**Comment by Goonersid** [comment]
@anjmao i do agree... We still have two select boxes in the same application where both behaviors are intended..Its kind of difficult to educate users beyond an extent :| A configuration would help us to a larger extent..

**Comment by anjmao** [comment]
@varnastadeus Probably we can add input called [markOnOpen]="false" to turn off this behaviour when needed.
