### ISSUE TITLE
Page getting slow.

### ISSUE THREAD

**Issue by kamal0912** [ng-select/ng-select#1061]
Hi,

I have a page with a table having 500 rows. Each row has 4 drop-downs. So total drop-downs become 2000. Page  is getting unusable due to lot of blur and focus events. Please suggest some solution.

**Comment by varnastadeus** [comment]
well, you shouldn't have 500rows at first place

**Comment by info-lvsys** [comment]
I think his comment is valid. We've noticed it really slow with just 3 dropdowns on a bootstrap modal. On top of that, ng-select doesn't work inside the bootstrap modal: the dropdowns show inside the modal and cause a modal scrollbar to appear - but that's a different issue. The performance is definitely noticeable. We're not sure why.

**Comment by varnastadeus** [comment]
I just tried with 2000 dropdown rendered and I had 0 issues

**Comment by info-lvsys** [comment]
Correct, there's no issue. I take that comment back. (oops)

We found out the problem lies elsewhere: if the page hosts a ton of angular elements, then the page's UI is slow in general, which impacts ng-select because it's an angular component itself (in contrast with the native select it replaces which isn't impacted by angular performance).

So, all in all: no performance issue to report, instead mostly a reminder that too much angular is just too much for the UI :) - thanks for the great work. ng-select works well

**Comment by trungjc** [comment]
> Hi,
> 
> I have a page with a table having 500 rows. Each row has 4 drop-downs. So total drop-downs become 2000. Page is getting unusable due to lot of blur and focus events. Please suggest some solution.

 [virtualScroll]="true" add this input help me resolve the issue

**Comment by b0yblake** [comment]
Already added [virtualScroll]="true" but still lagging... 
I had complex multiple forms (use add so many attributes) => when disable <ng-select> it will not lag anymore. So tied for this case.
