### ISSUE TITLE
Multiselect checkbox validation in reactive forms

### ISSUE THREAD

**Issue by snayak46** [ng-select/ng-select#1064]
IF the form is submitted without even clicking on multi select drop down, ng-invalid class doesnt appear as a result of which validation is not happening

**Comment by varnastadeus** [comment]
there is example with validation in https://ng-select.github.io/ng-select#/forms

**Comment by snayak46** [comment]
It is for Single Select and not for multi Select.

For Single select , i was able to do the validation

**Comment by varnastadeus** [comment]
there shouldn't be real difference between multiple or single select, required checks if value is selected at all

**Comment by Chiragsorathiya** [comment]
Hello there, 
can you give me one example with required validation?

**Comment by MacGyver27** [comment]
I have the same problem here.. I am on v2 because of Angular 7 version. 

Anyway the problem is when dealing with multiple and behaving the "tags" way. The form control value is an array and validators fail. Required validator will pass but some regex patter will only mach when the value array contains single value - otherwise it invalidates the whole form control.
