### ISSUE TITLE
cannot open the list after maxSelectedItems is reached

### ISSUE THREAD

**Issue by helif** [ng-select/ng-select#1131]
Cannot open the items list when "maxSelectedItems" property is set and the number of selections is reached.

The problem aggravates when you have the "clearable" property set to false.

<ng-select [multiple]="true"  [clearable]="false" [maxSelectedItems]="2"></ng-select>

Any workaround will be highly appreciated as there is no way to open the list and edit the selections.

Thanks!

**Comment by varnastadeus** [comment]
this is by design

**Comment by Saqib92** [comment]
Please Add this Feature.

**Comment by catadnl** [comment]
Hello,
This becomes an issue when you have some other **ng-multi-label-tmp** template implemented **without the inline clear** option because the width of the select doesn't allow you to display all the selected elements.

```html
<ng-select
  [items]="data | async"
  bindLabel="label"
  bindValue="value"
  [searchable]="true"
  multiple="true"
  maxSelectedItems="10"
>
  <ng-template ng-multi-label-tmp let-items="items" let-clear="clear">
    {{ items.length }} {{ 'Selected items' }}
  </ng-template>
</ng-select>
```
This code will produce something like this

<img width="209" alt="Screenshot 2020-09-04 at 15 03 46" src="https://user-images.githubusercontent.com/11778216/92237330-d81a7c00-eebf-11ea-9f8e-77d787f8db4b.png">

 In this case there is no way to reduce the number of selected elements without opening the Select so the user will be stuck.

@varnastadeus maybe this issue should be reopened or if you have any workaround for this use case, I would really appreciate it.

**Comment by kishoreandra** [comment]
> I have **fixed** above issue changing maxSelectedItems values in the open and close events. By default the value will be set as options array length when it opens once the value will be changed to required limit once it's closed that close event will be executed with in the method set that limit to array length. **_This method works for me._**

This saved me, thanks for sharing mate 🙏
