### ISSUE TITLE
Issue with custom class applying

### ISSUE THREAD

**Issue by iamdebodon** [ng-select/ng-select#1199]
Hi,

I have applied some custom class to my application, which was working fine with the old version of @ng-select. As I took the latest update I got that the class are not being applied to the drop down, if it is not append to body.

As I inspect and found that if appendTo="body" is passed the dropdown is taking the ng-select class, i.e., custom class which result of apply of the classes. But not in vice-versa.

For your reference shared a stackblitz link: https://stackblitz.com/edit/ng-select-7g7jxr

Thanks.

**Comment by varnastadeus** [comment]
read about this https://angular.io/guide/component-styles#view-encapsulation and 
https://github.com/ng-select/ng-select#custom-styles

**Comment by bhaskerchari** [comment]
@varnastadeus ,

I believe the issue what @iamdebodon trying to convey is not clear.

I also recently upgraded the library and I also faced the same issue with custom class not getting appended to the class list when I inspect the DOM which I will try to make it clear below.

Before Upgrade:

// For appendTo="body" attribute added in one case and not added in another case
<ng-select class="custom-class"></ng-select>
<ng-select class="custom-class" appendTo="body"></ng-select>

In both the above mentioned cases when dropdown is opened and inspected we get to see the class getting added to <ng-dropdown-panel/> component like below

<ng-dropdown-panel class="ng-dropdown-panel ng-select-bottom **custom-class**"></ng-dropdown-panel>


After Upgrade to latest:

// If appendTo="body" attribute is not added then on inspect
<ng-select class="custom-class"></ng-select>

<ng-dropdown-panel class="ng-dropdown-panel ng-select-bottom"></ng-dropdown-panel>

// If appendTo="body" attribute is added then on inspect
<ng-select class="custom-class" appendTo="body"></ng-select>

<ng-dropdown-panel class="ng-dropdown-panel ng-select-bottom **custom-class**"></ng-dropdown-panel>

So the bottom line is after upgrading to latest custom-class is getting added to <ng-dropdown-panel/> component only if appendTo="body" attribute is added otherwise it is not getting added which is not the case with the older version.

I hope I made the issue clear.

Thanks,
Bhasker

**Comment by iamdebodon** [comment]
@varnastadeus, as @bhaskerchari mentioned that's what I was trying to convey.

Will you look into it?

**Comment by varnastadeus** [comment]
It was changed because of https://github.com/ng-select/ng-select/issues/1035 and you only need a custom class to be applied when `appendTo` is used because dropdown is separated from the control, without `appendTo` you can use 
```css
.ng-select.custom-class .ng-dropdown-panel
```

**Comment by afiqwazien** [comment]
In my case, i was figuring out why the custom class was not applied to the dropdown even when I already set `appendTo` to body. 
If anyone faced the same issue as mine, just make sure you are using the attribute `class` instead of `ngClass`.

**Comment by shruti-ahuja** [comment]
Any success with it? Facing the sam issue.

> In my case, i was figuring out why the custom class was not applied to the dropdown even when I already set `appendTo="body"`.
> If anyone faced the same issue as mine, just make sure you are using the attribute `class` instead of `ngClass`.

**Comment by akalitenya** [comment]
> In my case, i was figuring out why the custom class was not applied to the dropdown even when I already set `appendTo="body"`. If anyone faced the same issue as mine, just make sure you are using the attribute `class` instead of `ngClass`.

Removing ngClass from ng-select works. ng-dropdown panel now has the same custom classes as ng-select (with apendTo="body").
