### ISSUE TITLE
SelectOnTab not working after upgrading to Angular 7.2.15

### ISSUE THREAD

**Issue by Jopnert** [ng-select/ng-select#1212]
---
name: Bug report
about: SelectOnTab not working anymore after update to latest angular 7(7.2.15)

---

**Describe the bug**
When selectOnTab=true and you tab to select an item, the item is selected an the dropdown is closed. But when you then tab to go to tge next control, the first item in the list is selected and you can't tab to the next control.

**Reproducbile example**
https://stackblitz.com/edit/angular-uecse4

**To Reproduce** 
1. Select the drodown
2. Type 4 to select "desc4"
3. Tab to select "desc4" and close the dropdown
4. Tab again to move to the next control

**Expected behavior**
"desc4" stays selected when tabbing to the next control

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Versie 75.0.3770.80 (Officiële build) (64-bits)

**Additional context**
When selectOnTab = false the behaviour is as expected
The stackblitz example in Angular 8 and i'm using 7.2.15, but the behaviour is the same
Thanks in advance for this very usefull component and hope you can provide a solution

**Comment by jagomf** [comment]
I have experienced NgSelect stopped working after moving `@angular-devkit/build-angular` from 0.7.0 to 0.12.1.

NgSelect seems to work with Angular 7.2.15 if you are using a rather "old" `@angular-devkit/build-angular`, e.g., 0.7.0, but it stops working after migrating to 0.12.1.

Mentioned migration **[is needed](https://github.com/angular/angular/issues/28123#issuecomment-453977348)** due to [import alias problem](https://github.com/angular/angular-cli/issues/13212).
