### ISSUE TITLE
appendTo body causes dropdown to have top position off

### ISSUE THREAD

**Issue by sangecz** [ng-select/ng-select#1234]
**Describe the bug**
when using appendTo="body" and dropdown position is at top of input: dropdown element's top position is off by approx. 20px, it overlaps input

**Expected behavior**
right top position of dropdown

**Screenshots**
with appendTo body:

<img width="415" alt="Screenshot 2019-06-21 at 14 24 19" src="https://user-images.githubusercontent.com/9822229/59922388-fae28100-9430-11e9-9c69-ce8fbcc0d3f5.png">

without it:
<img width="350" alt="Screenshot 2019-06-21 at 14 31 24" src="https://user-images.githubusercontent.com/9822229/59922601-704e5180-9431-11e9-8105-7bdb831e51a2.png">

**Comment by abhishek-mittal** [comment]
same problem here

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by sangecz** [comment]
@abhishek-mittal actually I found that this works for me (global styles):
```
 .ng-dropdown-panel.YOUR-CLASS {
    &.ng-select-top {
      margin-top: -10px;
    }
    &.ng-select-bottom {
      margin-top: 10px;
    }
}
```

**Comment by abhishek-mittal** [comment]
@sangecz it still didn't work as i put appendTo="body" as well

**Comment by HDinger** [comment]
Happens for me, too. Here is an example: https://stackblitz.com/edit/angular-jjbbq4
Just add so many entries, that the items span multiple lines:

<img width="509" alt="Bildschirmfoto 2019-06-28 um 14 10 34" src="https://user-images.githubusercontent.com/7457313/60341354-8074ac80-99ae-11e9-82c4-3348a3332ced.png">

For me, a workaround could be to manually enforce the repositioning with every add/delete with the `adjustPosition` method. However this [line](https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-dropdown-panel.component.ts#L180) prevents it for dropdowns that are opened to the top, which may also be the cause for this bug.

**Comment by varnastadeus** [comment]
@HDinger That `if` is intentional because when the dropdown position is `top`, control grows to bottom and dropdown is not overlaying. In your provided example, document.body has limited height and after control grows the whole body gets shifted. 

I am not sure how real is this setup. E.g. if you set `height: 500px` on body it works fine

**Comment by HDinger** [comment]
@varnastadeus I see the point. However we have cases in which the input grows to the top. 
![dropdown](https://user-images.githubusercontent.com/7457313/60424791-61b22800-9bf1-11e9-8148-41c6cf862793.gif)

In our case the problem occurs because of a two column layout. When the input grows some elements shift to the other column. Thus the position of the input changes, but the dropdown is not updated. https://stackblitz.com/edit/angular-xeigh4

**Comment by HDinger** [comment]
Thanks a lot @varnastadeus 👍
