### ISSUE TITLE
options not filtered correctly when using ngOptionHighlight

### ISSUE THREAD

**Issue by ronbiter** [ng-select/ng-select#1244]
Please fill below information if issuing a bug report. 
### Expected behaviour
options in the dropdown should filter according to search term

### Actual behaviour
the options are not filtered correctly (see your example page https://ng-select.github.io/ng-select#/forms the last example)

### More Info
ng-select version: 2.20.3

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: YES
![Capture](https://user-images.githubusercontent.com/9498236/60587081-391a6180-9d9c-11e9-9bfa-bd5e8eb756b6.PNG)

**Comment by LKU4** [comment]
I spent some time this morning to find source of this problem and I believe the cause lies in new trackByFn for dropdown options:
https://github.com/ng-select/ng-select/commit/0afa9c180aedcf8d8474dc2defd7804b1b44d51c

The list of options in dropdown is actually filtered correctly, and it is always cut down to correct number of options. You can even click a "wrong" option, and it turns out it's actually a correct one underneath. The only thing that doesn't work properly is displaying option labels in rendered HTML.

The current trackByOption looks like this:
```
trackByOption = (_: number, item: NgOption) => {
        if (this.trackByFn) {
            return this.trackByFn(item.value);
        }

        return null;
    };
```
If you do not supply your own trackByFn, it will return null for all options by default. I believe this means that Angular won't detect changes between swapped options and will see no need to re-render them, causing the problem. I think the default implementation should just return the whole item, so it can always compare object identity.

We can workaround this bug in current version by supplying our own trackByFn to ng-select component:
```
[trackByFn]="trackByFn"
```
```
trackByFn(item: any): any {
    return item;
}
```

Some other issues that I believe concern this bug:
#1181
#1218
#1229

**Comment by varnastadeus** [comment]
@LKU4 you are right, it was a bad idea to return null by default

**Comment by spitfjre** [comment]
This still does not work for me in v3.0.1. Only by providing own `tackBy` function.

**Comment by varnastadeus** [comment]
it does work in demo page
