### ISSUE TITLE
clear all event

### ISSUE THREAD

**Issue by AmitBuchnik** [ng-select/ng-select#1313]
the clear event is fired after the items are removed.
how can i set a confirmation dialog before clearing all?

**Comment by allencart** [comment]
Up for this

**Comment by JoseManuelFV** [comment]
Can be dirty solution...
You can use [ngModel] and (ngModelChange) to save oldData (before clear event call)
And in your listen clear function => set confirmation dialog.
If confirm dialog => Clear
If deny dialog => ngModelValue = oldData.

In my opinion... The event clear would have fired before to delete all data. At the present time this method:
-call after delete data
- "data event" is empty (when you use event.emit(event data) )

This issue has been since 11/19. But we are already in 4/21. I answer in case it works for someone

**Comment by Schwankenson** [comment]
Any progress on this? I need confirmation dialog, too

**Comment by Schwankenson** [comment]
I now added a <div> as wrapper around <ng-select> and put an own button in this rwapper below ng-select. This button can then be places absolute where you want it (in my case top right). And you can add custom function to it.
