### ISSUE TITLE
Sort feature for search result 

### ISSUE THREAD

**Issue by thankikaushik** [ng-select/ng-select#1409]
**Ability to sort search result.**
I have very large data under ng-select. So when user goes for some  item search there are many possibilities of matching data. So I want so sort search result so that i can easily lead them to perfect match based on my custom rules.  

**Describe the solution you'd like**
I would like to have ability to provide custom sort feature for search result items.

**Additional context**
My detailed problem can be found at` https://stackoverflow.com/q/58646348/3264939`

**Comment by Vgratioulet** [comment]
I think the point is to be able to sort the result after the initial loading of [items], so to be able to use already selected items for displaying next results. How could we do that ?

**Comment by lzilioli-prism** [comment]
I wanted to +1 this request and provide my use case.

In our application we use [fuzzy-search](https://www.npmjs.com/package/fuzzy-search) for filtration in a lot of our application. This package takes a search term and a list, and returns the list, **ordered by rank**. Presently, we use this with mat-select in the `searchFn` to determine if a result should show up or not, however the filtered list is then displayed by the results original order, rather than the ideal ranking that is determined by fuzzy-search.

At present, I am attempting to implement the suggestion over on this [stack overflow post](https://stackoverflow.com/a/58646488/239242), but it would be great if this was supported natively by ng-select.
