### ISSUE TITLE
when appendTo="body" and using custom header template to  search, ArrowDown, ArrowUp & Enter won't work.

### ISSUE THREAD

**Issue by LilTwo** [ng-select/ng-select#1488]
example: 
https://stackblitz.com/edit/angular-znc8gc?file=src/template-search-example.component.html

In my use case, I have to set `appendTo="body"` and customize search control in header template, but in this case, I can't scroll up or down using keyboard when focusing in custom search input, neither select an item by Enter key.

**Comment by akashthakur05** [comment]
@LilTwo  Had You Got any solution for above

**Comment by jupin-r** [comment]
This issue should be active because the error is reproducible.
I prepared playground with difference (wihout appendTo vs. appendTo=body). Each example has different behavior

https://angular-v4mxn1.stackblitz.io

Without append
------------------
1. Click to ng-select
2. Click to Custom search input
3. Press Arrow down/up
4. The items are selected by arrow up/down. This behavior is alright.

With appendTo=body
------------------------
1. Click to ng-select
2. Click to Custom search input
3. Press Arrow down/up 
4. **Error: No items are selected by arrow up/down.**

**Comment by akashthakur05** [comment]
```
	<ng-template *ngIf="searchable" ng-header-tmp>
		<div class="d-flex align-items-center">
			<input
				type="text"
				class="w-100"
				nbInput
				[placeholder]="'Start Typing '"
				(input)="select.filter($event.target.value)"
				(change)="$event.stopPropagation()"
				(keydown)="select.handleKeyDown($event)"
			/>
			<i class="fas fa-search fa-lg pl-2 text-gainsboro"></i>
		</div>
	</ng-template>
```

I Used this using my custom template and it solved the problem

**Comment by jupin-r** [comment]
@akashthakur05 nice solution, thanks.

I think that this bug sould be fixed even though awesome workaround exists.

**Comment by akashthakur05** [comment]
@jupin-r  I totally agree with you, I think they are not active.
