### ISSUE TITLE
What is required to enable Angular 9 support?

### ISSUE THREAD

**Issue by mbruning24** [ng-select/ng-select#1519]
**Is your feature request related to a problem? Please describe.**
Would love to see the package released with angular 9 support.

**Describe the solution you'd like**
When installing ng-select 3.x+, no peer dependency support warnings for angular 9.x

**Additional context**
There is currently a locked issue #1499 with no communication as to what might be required to help the Angular 9.x support roadmap. Some common sense might point to making sure all the tests pass and such, but my team and I are using ng-select in our application, which we've just upgraded to Angular 9. We are interested in seeing if there's anything that we might be able to do to help this roadmap in the way of contributions, but I can't ask any of these questions on #1499 (it being locked and all 🤣 ).

Anecdotally, while we do not use 100% of the ng-select features, all of the features that we do use do not seem to have any issues or bugs with angular 9. Interested in hearing what you all think!

Thanks for the awesome plugin.

**Comment by steve-todorov** [comment]
It looks like #1499 got locked due to heated comments and I hope this does not transfer here.

It would be helpful if the maintainers could point out what needs to be done here in order for Angular 9 support to be implemented (or if there is anything actually needed other than bumping the peer dependency versions)

**Comment by pdrakos** [comment]
I bumped the version and works in my angular9 project.

**Comment by samyue** [comment]
A quick support to the new major version 9 will be great! Many other libs of angular have already supported angular 9, such as Angular material, ng-bootstrap, ngrx, etc.  This lib is great, but please be quick on this, even a Beta/RC version is OK, since we only used a small set of features.

**Comment by daniel-seitz** [comment]
It seems like in #1499 there is a misunderstanding in what peer dependencies are or which part of the warning is being looked at.

With the current version 3.7.2 and angular 9 I get this warning:
warning " > @ng-select/ng-select@3.7.2" has incorrect peer dependency "@angular/common@>=8.0.0 <9.0.0".
warning " > @ng-select/ng-select@3.7.2" has incorrect peer dependency "@angular/core@>=8.0.0 <9.0.0".
warning " > @ng-select/ng-select@3.7.2" has incorrect peer dependency "@angular/forms@>=8.0.0 <9.0.0".

Of course since in this file https://github.com/ng-select/ng-select/blob/master/src/ng-select/package.json we have the following entries:

  "peerDependencies": {
    "@angular/common": ">=8.0.0 <9.0.0",
    "@angular/core": ">=8.0.0 <9.0.0",
    "@angular/forms": ">=8.0.0 <9.0.0"
  }

My understanding is: ng-select only works within Angular version 8.x.x

Why not use this instead?

  "peerDependencies": {
    "@angular/common": ">=8.0.0",
    "@angular/core": ">=8.0.0",
    "@angular/forms": ">=8.0.0"
  }

Then we can see if bugs arise.
We should get rid of the warning when npm /yarn install.

**Comment by andrejm7** [comment]
update please?

**Comment by benjmac** [comment]
> I bumped the version and works in my angular9 project.

What exactly did you change to make it work? I don't have the option to downgrade angular versions at this point. Thanks!

**Comment by daniel-seitz** [comment]
@benjmac nothing, just use the latest version of this package. you see a warning but it should work out of the box anyway.

**Comment by benjmac** [comment]
> @benjmac nothing, just use the latest version of this package. you see a warning but it should work out of the box anyway.

Interesting, I'm not getting any warning. My issues is the dropdown isn't selecting anything once opened. Like it's not registering the click to set the form value. I've confirmed the html and CSS seem to be okay, not blocking anything.

**Comment by martinbatun** [comment]
would it take a long time for the library to update incompatibility with angular 9? I think that the already migrated projects that make use of this are demaciated

**Comment by RichetGuillaume** [comment]
@benjmac  A pull request is ready for fix that 
https://github.com/ng-select/ng-select/pull/1571
Thanks to @wclaibor
