### ISSUE TITLE
StrictTemplates and async does not compile.

### ISSUE THREAD

**Issue by jessebuitenhuis** [ng-select/ng-select#1581]
**Describe the bug**
If the strictTemplates option is true (tsconfig.json > angularCompilerOptions), and a async pipe is used in the [items] input, the build does not compile.
A workaround is to add an empty array fallback, but it's not ideal.

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. tsconfig.json: set angularCompilerOptions.strictTemplates = true
2. Create a template with `<ng-select [items]="items$ | async"></ng-select>
3. Try to compile

**Expected behavior**
I expect [items] to be typed `any[] | null`.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: n/a

**Additional context**

**Comment by kimdah3** [comment]
Following your steps doesn't give me a build error and an example was not provided

**Comment by bbarry** [comment]
I don't think this is possible to demo on stackblitz because they don't expose tsconfig for editing.

Binding to async values gives an error when strict null checks are enabled in the angular template compiler with the typescript options in angular 9:

"angularCompilerOptions": {
  "fullTemplateTypeCheck": true,
  "strictInjectionParameters": true
}

https://angular.io/guide/typescript-configuration#typescript-configuration-1

**Comment by sweco-senari** [comment]
With angular 10 more people are going to use strict mode and therefore bump into this issue.
