### ISSUE TITLE
IE11 + multiselect placeholder align

### ISSUE THREAD

**Issue by Hesesses** [ng-select/ng-select#160]
Please fill below information if issuing a bug report. 
### Expected behaviour
Placeholders should be aligned correctly when using multiselect

### Actual behaviour
![image](https://user-images.githubusercontent.com/2721970/33794683-f31417f6-dcd8-11e7-80f0-73502fd915b9.png)

### More Info
ng-select version: 0.12
browser: IE11

reproducible in demo page: [YES]
https://ng-select.github.io/ng-select#/forms <- multiselect

**Comment by anjmao** [comment]
Thanks for reporting @Hesesses :)

**Comment by varnastadeus** [comment]
https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview

Looks like it's browser bug, I suggest to align it internally or not to use deprecated clients :)

**Comment by travis1234** [comment]
@Hesesses Sorry to revive a closed issue but it would be really good to get an actual fix or documented workaround for this issue.

IE11 is still a common browser in corporate environments where it's not as simple as just upgrading the browser. It's still the 6th most used browser with 3.14% market share. https://www.w3counter.com/globalstats.php

At this point in the time I'm going to have drop ng-select from my project which is a shame because it's awesome and you guys have done some great work.

Anyway hopefully you might reconsider supporting the browser. I know it's huge pain but I think there is still some value in it for developers who are stuck having to support it.

**Comment by varnastadeus** [comment]
@travis1234 currently we are not planning to change base style. You could always add your custom style to try to overcome this issue. 

In the future we plan to have multiple themes like bootstrap and material so user could include desired theme in his bundle. Bootstrap theme should not have this problem, since we won't use `flex` layout in it.

**Comment by varnastadeus** [comment]
@Hesesses @travis1234 This commit f94f4e6 should fix this issue. I have checked on IE11 and it looks fine.

**Comment by Hesesses** [comment]
awesome!

**Comment by travis1234** [comment]
@varnastadeus Thankyou!
