### ISSUE TITLE
Dropdown position not updated on multiselect option removal

### ISSUE THREAD

**Issue by lonerzzz** [ng-select/ng-select#1649]
**Describe the bug**
When removal of a multiselect option item results in the size change to the input box, the dropdown is not resized, leaving a gap between the input and the dropdown.

**Reproducible example**
Screenshots are shown instead of an example

**To Reproduce** 
Create a multiselect option field that does not close on select and fill it with enough selections so that it just spans more than one line. Then remove the option causing the input to span to the second line. On removal of the option, the dropdown menu position is not updated and a gap is present between the input and the dropdown menu.

Attempts to workaround by setting a fixed size for the input were possible but involved adding css rules to numerous internal portions of the selector.

**Expected behavior**
When an option is removed that forces a smaller resizing of the input, the open dropdown should move accordingly. 

**Screenshots**
As can be seen, the removal of the "Steele Industrial" option in the example results in an input resize but no corresponding movement of the dropdown so there is a gap in the display.

![CaptureBefore](https://user-images.githubusercontent.com/3473145/84538155-2b18d480-acbf-11ea-98f0-41c81b7b7120.JPG)
![CaptureAfter](https://user-images.githubusercontent.com/3473145/84538166-2f44f200-acbf-11ea-9234-40da84d5d19f.JPG)

**Desktop:**
 - OS: Windows 10
 - Browser: Latest Chrome as of issue creation date
 - Version Latest version of ng-select as of issue creation date

**Additional context**
None

**Comment by DepickereSven** [comment]
I think this is linked to the following issue: https://github.com/ng-select/ng-select/pull/1601

**Comment by kotmatpockuh** [comment]
Also, have the same issue... @DepickereSven any ETA to fix this?

**Comment by DepickereSven** [comment]
@kotmatpockuh I won't fix the bug. I explained what was wrong. The reason why I won't fix it because it would take to much time for me. I currently don't have that much time. Instead I looked for an alternative. The alternative is [Ng-Zorro](https://github.com/NG-ZORRO/ng-zorro-antd). It also has a [ng-select component](https://ng.ant.design/components/select/en#ng-content). I used a wrapper to consume nog-select and I switched it with nog-Zorro everything works for me. This bug doesn't longer exist. The only thing that nog-Zorro doesn't have is the input `labelForId`.
