### ISSUE TITLE
Meet Lighthouse requirements

### ISSUE THREAD

**Issue by Hoopou** [ng-select/ng-select#1798]
I Made a PWA App in Angular and my app met all lighthouse requirements at 95% or more before i added ng-select to my project.
Now I am not. 

Lighthouse is telling me : 3 major warnings:

![image](https://user-images.githubusercontent.com/23001107/98578152-f66b7200-228a-11eb-8b18-252b50815fb4.png)

![image](https://user-images.githubusercontent.com/23001107/98578199-03886100-228b-11eb-9127-8a77cd8e673c.png)

For now its not a big deal, but soon I want to put my pwa app on the app store and **I have to** meet the requirements in order to publish my app.

Thanks

**Comment by artopaavola** [comment]
First two (**ARIA input fields do not have accessible names** and **Elements with an ARIA [role]...**) are fixed in [v5.0.10](https://github.com/ng-select/ng-select/releases/tag/v5.0.10).

For the third one **Form elements do not have associated labels** you need give the id of the element that is used as the label for the component.

![image](https://user-images.githubusercontent.com/2992255/103521644-c94dd100-4e81-11eb-8274-30aa37d5fd94.png)

**Comment by varnastadeus** [comment]
Closing this based on the comment above ⬆️
