### ISSUE TITLE
Item not clickable 

### ISSUE THREAD

**Issue by flohw** [ng-select/ng-select#1833]
**Describe the bug**
When using a component getter to provide the `items` attribute of `ng-select` none of the items are clickable (but works fine when tapping `enter` on the keyboard)

**Reproducbile example**
[Example](https://stackblitz.com/edit/angular-ivy-jdozwg) which reproduces described behaviour

**Expected behavior**
Each items should be clickable to be selected

**Desktop (please complete the following information):**
 - OS: linux
 - Browser firefox
 - Version 84
 - ng-select version : 4.0.4 with angular 9.1.12

**Smartphone (please complete the following information):**
Not tested

**Additional context**
I read this comment https://github.com/ng-select/ng-select/issues/1120#issuecomment-477198661 but I don't know how I can make it differently when I need a dynamic list based on data in the same component. Should I use observable? 

Thank you

**Comment by flohw** [comment]
Observable works fine. I didn't think about it earlier...

I let you close the thread if that's the way to go and the issue won't/can't be fixed.

**Comment by jcbvm** [comment]
I encountered the same, and I don't understand why this would not work out of the box...
Is it because push state is used as change detection?

For example, when doing the following:
[items]="currentUser.roles"

The select is just not working properly, items are shown but not clickable...
The items property only seems to work for static lists...

**Comment by cmrabet** [comment]
I have this issue. 

How to use observables?
