### ISSUE TITLE
Resizing screen breaks dropdown position

### ISSUE THREAD

**Issue by alexey-shakura** [ng-select/ng-select#1837]
**Describe the bug**
When I try to resize screen width while the select is opened, the dropdown panel position isn't updated. Calling `adjustPosition` on dropdownPanel doesn't help.

**Reproducible example**
Try demo of appendTo and resize the width of screen

https://stackblitz.com/edit/z9k76d--run?file=src/append-to-example.component.html

**Expected behavior**
When resizing screen with opened select I expect to update the dropdown position. Or provide an API so developer can explicitly update the positioning when needed.

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Browser: Chrome 87
 - Ng-select: 4.0.4
 - Angular: 9.1.3

**Comment by Jonah-Jordan** [comment]
+1

**Comment by ebakep** [comment]
Faced the same issue, any updates here ?

**Comment by casper5822** [comment]
Same for me with angular 10.
It seems related to appendTo="body" . Also in the official stackblitz there is the same problem. It works with appendTo set on other components or without it at all.

**Comment by Jonah-Jordan** [comment]
Still same issue

**Comment by pvds** [comment]
`adjustPosition` does not update the x position of the dropdown: [source code](https://github.com/ng-select/ng-select/blob/cafe3db2c045257f4d329ed3bc81d227b118effb/src/ng-select/lib/ng-dropdown-panel.component.ts#L188)

Since `_updateXPosition()` is private I don't see a way to recalculate the horizontal position at the moment.

I would suggest to expose both the update position methods and/or add an `Input()` property (boolean) to recalculate the dropdown position when the `appendTo` property is used.
