### ISSUE TITLE
Feature request: 'Select all' button

### ISSUE THREAD

**Issue by swymmwys** [ng-select/ng-select#184]
Hi.
It will be great if you can include an optional setting for a 'ng-select' which allow users to specify a 'Select all' button (or a trigger button - select/unselect all).

Thanks.

**Comment by anjmao** [comment]
I thought it would be good to implement this before v1 release because this feature will show how to use ng-select public api. Here is some progress how it can look. I created new template directives for header and footer so it will be possible to have flexible customisations. Just need to spend some more time polishing public api before the can make first release.

<img width="723" alt="custom_header_footer" src="https://user-images.githubusercontent.com/3028012/34976202-19103344-fa9e-11e7-9bfe-61655607b4dc.png">

In user component
```ts
    selectAll(ctx: NgSelectComponent) {
        ctx.itemsList.items.forEach(item => ctx.select(item));
        ctx.detectChanges();
    }

    selectNone(ctx: NgSelectComponent) {
        ctx.itemsList.items.forEach(item => ctx.unselect(item));
        ctx.detectChanges();
    }
```

There is are problem that we need to separate component public api from internal so we are not making breaking changes in the feature versions. I'm thinking about creating ngSelectService which can be injected and have public api.

```ts
    constructor(private ngSelectService: NgSelectService) {}

    selectAll(cmp: NgSelectComponent) {
        const ctx = this.ngSelectService.getContext(cmp);
        ctx.items.forEach(item => ctx.select(item));
        ctx.detectChanges();
    }
```

**Comment by swymmwys** [comment]
Great, looks nice!

2018-01-16 10:33 GMT+03:00 Andžej Maciusovič <notifications@github.com>:

**Comment by anjmao** [comment]
@swymmwys Checkout 0.15.1 version :)

**Comment by bulkasamurai** [comment]
Hi. @anjmao buttons "Select all" and "Select none" disappears with a delay when you close the dropdown. Could you fix this for the release?

http://g.recordit.co/Kjk26jJ0xi.gif

**Comment by varnastadeus** [comment]
@bulkasamurai can you reproduce it in demo page?

**Comment by mohitj27** [comment]
hi can you tell me the solution when i add a button to multiselect dropdown it doesn't appear 
suggest any method to me for this

**Comment by mtpultz** [comment]
@mohitj27 see this [Stackoverflow](https://stackoverflow.com/questions/51518133/how-to-add-select-all-functionality-to-ng-select-in-angular-5/54544217#54544217) answer for an example of using the header template.

**Comment by saeedarshad** [comment]
> @swymmwys Checkout 0.15.1 version :)

Select all also select the items which do not filter in our search. e.g if we have 100 items in our drop down and our search gives us 20 items but when we do Select All it select all 100 items.It should only select 20 items.Currently Is there any way to do it .

**Comment by uttahb** [comment]
> @mohitj27 see this [Stackoverflow](https://stackoverflow.com/questions/51518133/how-to-add-select-all-functionality-to-ng-select-in-angular-5/54544217#54544217) answer for an example of using the header template.

Hi @mtpultz, I have done something similar to this answer, the problem I am facing with is to have a keyboard navigation to the header template. Is there any work around for that?
