### ISSUE TITLE
Multi-Select: Option for number of displayed options

### ISSUE THREAD

**Issue by TheOfficialLoren** [ng-select/ng-select#1846]
**Is your feature request related to a problem? Please describe.**
I have a dropdown list that's prefilled with 5 or 6 options that are all selected. The dropdown list becomes very big and spanning 4 or 5 rows.  In my scenario I need the multi-select box to stay 1 row regardless of the amount of items selected.

**Describe the solution you'd like**
It'd be nice if there's an option `totalDisplayedSelectedItems`. When set, the dropdown list would show something like: 
" Option1  Option2  +3 Others"

**Describe alternatives you've considered**
An alternative could be displaying none of the selected items until you open the list and see a checkbox next to each selected option.

**Comment by yashnit229** [comment]
For those that don't know, instead of just setting a JS variable, you could set a custom attribute on the dropdown using .attr(), then retrieve that on .change(). This is nice and helps if you have multiple dropdowns that need this limitation. 
Can this be doable WITHOUT a <select> and <option> format? Such as, just regular DIV's that have a class applied to them when clicked? Such as an 'active' class for instance that would visually show them as active [Web Application Development Company ](https://www.catamerica.com/application-development/)

**Comment by yashnit229** [comment]
For those that don't know, instead of just setting a JS variable, you could set a custom attribute on the dropdown using .attr(), then retrieve that on .change(). This is nice and helps if you have multiple dropdowns that need this limitation.  
[Web Application Development Company ](https://www.catamerica.com/application-development/)
