### ISSUE TITLE
Properties to customize design

### ISSUE THREAD

**Issue by kmathy** [ng-select/ng-select#191]
Please fill below information if issuing a bug report. 

Firstly, a BIG thank for this plugin, it saves me a lot of tedious work! :)

### Expected behaviour
It can be interesting to have some properties only to customize some parts of the select and the dropdown.

For example: [customNgControlClass]="['custom-1', 'custom-2']" --> Applies for .custom-1 and .custom-2

It can also be interesting to have separated properties to design the plugin.
### Actual behaviour
At the moment, I need to add in my global styles `!important`. It works, but can't really override the style properties.
### More Info
ng-select version: 0.14.4

browser: Google Chrome Version 63.0.3239.132 

reproducible in demo page: NO

**Comment by anjmao** [comment]
Hi @kmathy There is similar issue registered https://github.com/ng-select/ng-select/issues/86 and this is know issue. Because we are bundling styles into component itself it is not possible to control in which order styles are applied. I can see only one possible solution to bundle styles in separate file and force user to include styles by himself. This will also give as a lot of flexibility like custom themes and easy styles overrides. @varnastadeus What do you think?

**Comment by varnastadeus** [comment]
@kmathy there is no need to use `!important`. You can just increase selector specificity which increase its weight. Check #156.

**Comment by kmathy** [comment]
@varnastadeus You're right, it works with your example, thank you. But with this way, are we able to customize all the ng-select component?

**Comment by varnastadeus** [comment]
if by customize you mean changing it appearance through css, then yes :)

**Comment by kmathy** [comment]
OK, thank you!! I gave a star for this project, I like it! :)

**Comment by anjmao** [comment]
@kmathy Thanks :)
