### ISSUE TITLE
How to avoid Space in tag or blank space should not allow in tag

### ISSUE THREAD

**Issue by ambujkhanna** [ng-select/ng-select#2174]
**Is your feature request related to a problem? Please describe.**
I have a case where space should not allowed in tag.

**Describe the solution you'd like**
I want if user press SPACE BAR then it should convert to tag similar to ENTER key press behavior instead adding space in same tag

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/3599739/206160066-dfce916e-4248-4357-bcda-9122552c84ec.png)

**Comment by Yupla** [comment]
Hi @ambujkhanna, I also had a specific validation case for tags what you can use is a function instead of just giving true to the [addTag] property. Here is my implementation of it :

in html of component : 
`[addTag]="addTagPromise.bind(this)"`

in .ts of the component : 
`addTagPromise: (name: string) => Promise<any>;

this.validationRegex = new RegExp('^[a-zA-Z0-9_\\-\\s]*$');
    this.addTagPromise = (name: string) => {
      return new Promise((resolve, reject) => {
          if (name.match(this.validationRegex)) {
            resolve( name );
          } else {
            // this reject doesn't display anything so you can call a toast or something to display the error to the user
            reject('Provided name is not correct, values must be alphanumeric or \- or \_');
          }
      });
    }
`

Hope this helped you.
