### ISSUE TITLE
bindValue support for nested objects

### ISSUE THREAD

**Issue by pupizoid** [ng-select/ng-select#219]
Hi there! Just used this awesome package and got stuck with `bindValue` don't work with embedded objects. Although `bindName` does! Please clarify this to me, is it a bug or this works as expected, i didn't find any info about this.

### More Info
ng-select version: 0.15.2
browser: Chrome
reproducible in demo page: https://plnkr.co/edit/4b9x0lxADf09zaNlzcss?p=preview (The `selectedCity` remains _undefined_ after any choice)

**Comment by anjmao** [comment]
Hi @pupizoid . It is not implemented yet as it is more complex as bindLabel, but this is indeed needed feature and will be implemented.

**Comment by varnastadeus** [comment]
Hi @pupizoid. Thanks for feedback. As @anjmao said it's not implemented yet. There was few reasons for that: 
1. There was no request
2. Complexity implementing it is higher than value from it since you can always get full object and `map` nested value. 

But that's definitely not the reasons not implementing it.

**Comment by pupizoid** [comment]
Ok, thanks for reply! Will await for it with patience. 😄

**Comment by pupizoid** [comment]
@anjmao, I've just tested - everything works as expected! Thanks for work!!!
