### ISSUE TITLE
Move selected options to top of the ng-select dropdown

### ISSUE THREAD

**Issue by sujith1201** [ng-select/ng-select#2332]
We have a scenario in which the selected values(single or multiple) must be displayed on the top of the ng-select dropdown values.
Is there any built-in feature in ng-select to achieve the functionality mentioned above?

**Comment by bhaskerchari** [comment]
Hey there!

We are also looking for a feature something like this because most of the ng-select dropdowns we use are multi select and user's expressed great desire of looking all the selections right at the top of the list when the dropdown is opened!

Can someone shed some light on this if there is a way or work around to achieve this in a generic way through out the application?

Thanks in advance!
