### ISSUE TITLE
Selected item is not scrolled into view when dropdown open

### ISSUE THREAD

**Issue by MarianBabic1** [ng-select/ng-select#2372]
**Describe the bug**
This only happens when we provide data items with already grouped children array with at least 2 optgroups. If item from any optgroup apart from 1st is selected and we open the dropdown, this item is highlighted but not scrolled into view.

**Reproducbile example**
[[Example](https://stackblitz.com) which reproduces described behaviour](https://stackblitz.com/edit/angular-pn225b-mhzrfy?file=src%2Fgroup-children-example.component.ts,src%2Fgroup-children-example.component.ts)

https://angular-pn225b.stackblitz.io/

**To Reproduce** 
1. Modify your demo example https://github.com/ng-select/ng-select/blob/master/src/demo/app/examples/group-children-example/group-children-example.component.ts so there are many items in 1st optgroup and scrollbar appears when dropdown is open, for example:
```
projects = [
        {
            id: 'p1',
            title: 'Project A',
            subprojects: [
                { title: 'Subproject 1 of A', id: 's1p1' },
                { title: 'Subproject 2 of A', id: 's2p1' },
                { title: 'Subproject 3 of A', id: 's3p1' },
                { title: 'Subproject 4 of A', id: 's4p1' },
                { title: 'Subproject 5 of A', id: 's5p1' },
                { title: 'Subproject 6 of A', id: 's6p1' },
                { title: 'Subproject 7 of A', id: 's7p1' },
            ]
        },
        {
            id: 'p2',
            title: 'Project B',
            subprojects: [
                { title: 'Subproject 1 of B', id: 's1p2' },
                { title: 'Subproject 2 of B', id: 's2p2' },
            ]
        }
    ]
```
2. Open dropdown, scroll down and select any item from 2nd optgroup (1st optgroup works fine), for example "Subproject 1 of B"
3. Open dropdown again
4. Selected item is not scrolled into the view. If we scroll down, we can notice that it is highlighted correctly though.

**Expected behavior**
Selected item is scrolled into view when dropdown open.

**Comment by MarianBabic1** [comment]
Suggested fix to ensure unique htmlId is generated for each item:
![image](https://github.com/ng-select/ng-select/assets/121797911/841e8b90-bbb1-4e42-abdd-c7d96a37ddce)

**Comment by ravindUwU** [comment]
Hi @pavankjadda any reason why this issue closed as not planned? 🤔

The underlying issue is that `ng-select` generates duplicate IDs for `.ng-option`s across `.ng-optgroup`s. For example, the DOM generated for 2 groups with 4 items each is,

```diff
 <div class="ng-option-disabled ng-optgroup" id="af9b8a726971">0</div>
-<div class="ng-option ng-option-child" id="ac55a7df4ad0-0">0.0</div>
-<div class="ng-option ng-option-child" id="ac55a7df4ad0-1">0.1</div>
-<div class="ng-option ng-option-child" id="ac55a7df4ad0-2">0.2</div>
-<div class="ng-option ng-option-child" id="ac55a7df4ad0-3">0.3</div>
 <div class="ng-option-disabled ng-optgroup" id="aa37936a854a">1</div>
-<div class="ng-option ng-option-child" id="ac55a7df4ad0-0">1.0</div>
-<div class="ng-option ng-option-child" id="ac55a7df4ad0-1">1.1</div>
-<div class="ng-option ng-option-child" id="ac55a7df4ad0-2">1.2</div>
-<div class="ng-option ng-option-child" id="ac55a7df4ad0-3">1.3</div>
```

I think the **correct fix** would be to include the group index in the generated IDs making them of the format `newId()-groupIdx-itemIdx`; i.e., `ac55a7df4ad0-0-{0,1,2,3}` and `ac55a7df4ad0-1-{0,1,2,3}` for the `.ng-option`s in the example above 🤔.

I noticed that this occurs only when the items are [pre-grouped](https://github.com/ng-select/ng-select/tree/c7d2b220128998be043d38ece0760714da2c2893/src/demo/app/examples/group-children-example); the component seems to work fine when items are a "flat" list.

I'm unable to work on this and submit a PR at the moment, but I've reproduced the issue and implemented a hacky _temporary fix_ at https://stackblitz.com/edit/ravinduwu-misc-angular-ng-select-grouping-fix?file=src%2Fapp.component.ts%3AL15 which changes [`ItemsList.mapItem`](https://github.com/ng-select/ng-select/blob/c7d2b220128998be043d38ece0760714da2c2893/src/ng-select/lib/items-list.ts#L232) via its prototype, to suffix the string `_fixN` (sequential `N`) to the `htmlId`.

**Comment by pavankjadda** [comment]
@ravindUwU not a priority right now. We have other prioritized (based on thumbs up) issues. Feel free to send PR.

**Comment by ravindUwU** [comment]
Thanks for confirming Pavan 🙂.

Seeing as this is an unresolved https://github.com/ng-select/ng-select/labels/bug, I'd humbly suggest labelling it as such, and possibly reopening it to clarify that contributions are welcome (as opposed to an issue that's closed because it's rejected/won't fix).
