### ISSUE TITLE
The `isOpen` prop will always be a boolean type

### ISSUE THREAD

**Issue by nzbin** [ng-select/ng-select#2393]
### Describe the bug

https://github.com/ng-select/ng-select/blob/6714b6535518834034bdf5d4b9a6e26b5049d546/src/ng-select/lib/ng-select.component.ts#L118

https://github.com/ng-select/ng-select/blob/6714b6535518834034bdf5d4b9a6e26b5049d546/src/ng-select/lib/ng-select.component.ts#L284-L286

As the input `isOpen` use booleanAttribute transform, it will always be a boolean type. When you pass a `undefined` value, it would be false, so the `_manualOpen` will always be `false`.

### Expected behaviour

The `isOpen` can be set to `undefined`

### What version of the library you see this issue?

13.2

### What version of Angular are you using?

Angular 18

**Comment by pavankjadda** [comment]
@varnastadeus @anjmao  I am currently this repo with community support. Currently Reviewing and accepting PRs, answering issues, fixing bugs (when time permits) and keeping up with Angular versions. 

However I can't merge simple PRs created by me since I don't have elevated access to `ng-select` organization. Would it be possible to provide me elevated access?

**Comment by danielsefton** [comment]
Just adding that we also experienced this. Seems to be a regression somewhere around v13+. Causes problems for component wrappers around ng-select where you have an optional input parameter for isOpen. Confused us as to why our dropdowns weren't opening at all after upgrading to Angular 18.
