### ISSUE TITLE
More than one ng-select are opened with the arrow button click

### ISSUE THREAD

**Issue by Filini** [ng-select/ng-select#289]
### Expected behaviour
When clicking the ng-select arrow to open it, the other ng-select dropdowns should close. Only one ng-select should be open at any given time. The behaviour is correctly implemented when the ng-select is opened by field focus.

### Actual behaviour
More than one ng-select stays open, when opening them with the arrow button.

### More Info
ng-select version: 0.22.0

browser: Chrome

reproducible in demo page: YES

**Comment by anjmao** [comment]
@Filini Thanks for reporting. This happens because this line of this line here https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-select.component.ts#L471 

As arrow button is inside select rect it is skipped. Need to check if it is possible to check if target is actually arrow btn and exclude it then.

**Comment by Filini** [comment]
thank you
