### ISSUE TITLE
Add ability to disable focus and blur events

### ISSUE THREAD

**Issue by Karasishka** [ng-select/ng-select#352]
### Expected behaviour
If user don't need focus and blur events - he should be able to deactivate them and ng-select not create these events

### Actual behaviour
Focus and blur events are creating for each of ng-select on page. If there is a lot of ng-selects on page (more than 10 or 20) - the page became very slow because on each click event it should check two events for each of ngselect on page (in my case it was more than 100 events)
### More Info
ng-select version: latest

browser: any

reproducible in demo page: no

**Comment by varnastadeus** [comment]
Ok, I have checked to see if there is actual issue here. Single `ng-select` adds 1 additional `focus` and `blur` event listeners. Each of those event listeners triggers events for corresponding `ng-selects`. Prove me wrong but I don't see any issues here and there is no way that `ng-select` could have performance impact.
