### ISSUE TITLE
Toggling show/hide of input causes duplication

### ISSUE THREAD

**Issue by carlhussey** [ng-select/ng-select#36]
I have an input that is wrapped in a `[hidden] `directive. This input is using my reactive form model for its binding. It appears that when I toggle this input from hidden -> shown -> hidden - > shown, it causes the default options within the input to duplicate. The model seems unaffected and contains the original data.

```
<span [hidden]="!inEditMode()">
  <ng-select formControlName="AttributeValue" [items]="valueOptions" [multiple]="true" bindLabel="Value" placeholder="Select one or more values" class="test"></ng-select>
</span> 
```

**Comment by anjmao** [comment]
@carlhussey By saying default options are you talking about `valueOptions`? Maybe you can update your issue and provider more code how it looks like or maybe you can take basic ng-select plunker example and create repro https://plnkr.co/edit/tjxQgDY2Pn8RRPsoVAa0?p=preview because I'm unable to reproduce this case. Thanks :)

**Comment by carlhussey** [comment]
This looks like it was an issue on my side. Wasn't able to reproduce in a a separate scenario.
