### ISSUE TITLE
Incomplete material theme in IE11

### ISSUE THREAD

**Issue by andreastroeger** [ng-select/ng-select#362]
### Expected behaviour
The ng-select material theme should look in IE11 as it looks in Chrome or Firefox.

### Actual behaviour
The bottom border of the div "ng-control" is been crossfaded from the div ".ng-value-container". Because of this, the dynamic underscore is not visible.

![material_design_ie11](https://user-images.githubusercontent.com/37435500/37515449-20afcb1e-290b-11e8-84f7-b8c90d09b233.png)

### More Info
ng-select version: 0.26.2

browser: IE11

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
I have looked into this issue and it seems IE11 has problems with  css `:after` element which is no surprise since it is crappy browser. I don't think we would support material theme for IE browsers. 

What can you try is to implement https://material.angular.io/guide/creating-a-custom-form-field-control and then apply some of styles like it was mentioned in #358
