### ISSUE TITLE
Tab select behaviour

### ISSUE THREAD

**Issue by granteagon** [ng-select/ng-select#370]
Please fill below information if issuing a bug report. 
### Expected behaviour
1. Type into searchable single select field.
2. Press tab when desired item is highlighted.
3. Highlighted item should be selected.

### Actual behaviour
1. Type into searchable single select field.
2. Press tab when desired item is highlighted.
3. Highlighted item is lost.

### More Info
ng-select version: 0.30.0

browser: Internet Explorer, Chrome

reproducible in demo page: YES

In a normal HTML5 single select, the highlighted value is preserved, as the highlighted value is implicitly also in selected state.  This might be best handled as an attribute in @ng-select/ng-select.

I am willing to do the coding.

Thanks

**Comment by anjmao** [comment]
Hi @granteagon, pressing tab should not select any element because tab function is to focus next focusable element, but do not change current selection, this is there enter should be used. I also looked at other components: https://selectize.github.io/selectize.js/ 
https://select2.org/
https://material.angular.io/components/autocomplete/overview

**Comment by granteagon** [comment]
I understand your point of view, however I disagree.

The fact that other projects have also missed this minor detail in behavior is not a convincing argument to me for ignoring the behavior.  I will accept that this should be an opt-in behavior using an attribute, but as I said before, tabbing out of a select in HTML5 when a value is highlighted, selects that value. Power users who keyboard navigate rely on this type of functionality.

**Comment by granteagon** [comment]
@varnastadeus for a native select:
1. Click on select so that it opens
2. Hit the down arrow so an active option is highlighted
3. Hit "TAB".

The value is not selected in your browser?

**Comment by granteagon** [comment]
@anjmao On Windows native select:
1. Type some letter that causes a selection
2. Tab out of field
-> Value is selected

On ng-select demo:
1. Type into searchable field so that a value is highlighted
2. Tab out of field.
-> Value is not selected

**Comment by johntseng** [comment]
@granteagon I had the same issue. This missing functionality is actually a deal-breaker with my accounting clients. Here's how I hacked around this deficiency:
```
  @ViewChild(NgSelectComponent) private set ngSelect(ngSelect: NgSelectComponent) {
    if (!ngSelect) {
      return;
    }
    ngSelect._handleTab = function() {
      if (this.isOpen) {
        if (this.itemsList.markedItem) {
          this.toggleItem(this.itemsList.markedItem);
        }
        else if (this.addTag) {
          this.selectTag();
        }
      }
    };
  }
```

@anjmao Like Grant, I would be happy to contribute this functionality as an option if there's a chance that it will get accepted.

**Comment by granteagon** [comment]
@johntseng I just forked it and did what I wanted.  Maybe it'll get added later.  Thanks for the code hint!

**Comment by johntseng** [comment]
@anjmao Do you think it might make more sense to have an option to have arrow keys select the item, mimicking the behavior on windows?

**Comment by varnastadeus** [comment]
I think we should consider implementing it as separate option.

**Comment by granteagon** [comment]
I can do a pull request for this if desired.

**Comment by varnastadeus** [comment]
@granteagon if it will be proper PR with test cases, then contributions are more than welcome 👍

**Comment by granteagon** [comment]
@varnastadeus It's a small change.  I will make it happen.

**Comment by angelo510** [comment]
Hi @granteagon,
I watched the issue and I just create a PR for this issue.
https://github.com/ng-select/ng-select/pull/391

**Comment by anjmao** [comment]
Hi @angelo510, thanks for PR. I added one comment to make it configurable, tab can select value by default, but it would be good to also keep current behaviour.

**Comment by granteagon** [comment]
#392 incoming with tests and documentation

**Comment by angelo510** [comment]
@anjmao Thanks for your review. I will make it work with [tabSelectsValue].

**Comment by anjmao** [comment]
@granteagon @angelo510 Since it is small change and your both PR's are not covering all cases I created new PR there I merged your changes and added some more logic. Clicking on tab should select value but also prevent default event and not jump to other element straight away, because it would confusing and user may not noticed that he actually changed selected value.

**Comment by granteagon** [comment]
@anjmao does this mean that the user will have to hit the tab key twice to get to the next field?  If so, I don't think that's a good idea.  People who have little technical knowledge will have to recognize an ng-select as a different kind of field that has a special requirement of their behavior.  This seems unnecessary and overly complicated.  Data entry people don't see an ng-select as any different from a normal html select and will have difficulty using the field.

**Comment by anjmao** [comment]
@granteagon 
1) In normal html select tab does not select value.
2) I changed [selectOnTab] to false by default, so current behaviour will work as original select.
3) React select also selects value on tab click but does not jump to other control http://jedwatson.github.io/react-select/

Can you find any select control which would select value on tab click and also jump to other field at the same time and point link here? I didn't found any.

**Comment by granteagon** [comment]
@anjmao Looks like you're right.  Thanks

**Comment by SamanthaAdrichem** [comment]
Thank you for this feature!

**Comment by shuaib786** [comment]
Hi i tried [selectOnTab] = true 
[selectOnTab] = “true” both showing rendering error 
Is this the correct syntax

**Comment by shuaib786** [comment]
Is there any update?

**Comment by varnastadeus** [comment]
use latest version

**Comment by saiyaff** [comment]
> @granteagon I had the same issue. This missing functionality is actually a deal-breaker with my accounting clients. Here's how I hacked around this deficiency:
> 
> ```
>   @ViewChild(NgSelectComponent) private set ngSelect(ngSelect: NgSelectComponent) {
>     if (!ngSelect) {
>       return;
>     }
>     ngSelect._handleTab = function() {
>       if (this.isOpen) {
>         if (this.itemsList.markedItem) {
>           this.toggleItem(this.itemsList.markedItem);
>         }
>         else if (this.addTag) {
>           this.selectTag();
>         }
>       }
>     };
>   }
> ```
> 
> @anjmao Like Grant, I would be happy to contribute this functionality as an option if there's a chance that it will get accepted.

@johntseng,
By doing so, didn't you get any build errors while executing `ng build --prod`?
Or the following which is '_Property '_handleArrowDown' is private and only accessible within class 'NgSelectComponent_'.'?
![image](https://user-images.githubusercontent.com/17147255/60248465-548af580-98e0-11e9-9495-656cd4309f18.png)

If yes, how did you overcome those?

**Comment by gerwintown** [comment]
@anjmao  

"In normal html select tab does not select value."

No, in normal html, the TAB key moves the cursor/focus to the next descending tabbable element.  Now it doesn't.

The question you were asked is why does the TAB key no longer move on to the next input focus.    

If your interest is in keeping it as close to native select, then violating tab key behavior by preventing default is the exact opposite of that goal.

Your answer would only apply to the question of allowing TAB to select an option, not why it selects the option AND prevents default behavior on moving focus.  Basically, your answer doesn't make any sense.

The entire point of "select on tab" would be to combine option selection with the native focus movement of TAB.  Why would anyone want to use TAB for select otherwise?  Just to replicate behavior of ENTER?  I don't think so, and I don't think any of the comments on this issue support that idea either.

Anyway, the most recent comment shows the real problem with this implementation:
1. We cannot override (using the work around posted in this thread for example) because _handleTab  is private.
2. We also cannot build our own function (on the blur event) now, because _handleTab closes the dropdown automatically when [selectOnTab] is false.

Because of those two impediments, it is now seemingly impossible to use this component and:
1. use tab to select an option
2. proceed to the next form item in the tabindex with one press of the tab key

Currently, it would have been better had you done nothing at all.  

I am fine with the opinionated nature of your defaults in keeping with native select, but I have a hard time understanding why it seems you are preventing native tab key behavior while allowing tab selection...

"Can you find any select control which would select value on tab click and also jump to other field at the same time and point link here? I didn't found any."

At least with Angular Material, you can write a directive to handle the blur event and define exactly the behavior that is desired.  And there are plenty of non-html software UIs where this is possible, which is why it is being requested in the first place (because we are likely writing Web-based UIs to replace legacy native applications).

Can you think of ANY *reason* why one would want to select with the tab key and not jump to the next field?  Can you think of any *reason* why one would want to select with the tab key and have to press it again to jump to the next field?

There should be a way to optionally cancel your prevent default event, if the developer desires to do so.  This way you can have your opinion, and we can give our users the behavior they demand.

**Comment by gerwintown** [comment]
Read this:
https://ux.stackexchange.com/questions/40796/what-intent-does-the-tab-key-convey

From the top answer:

"However, if you look at how Tab should behave in a Combo Box (similar to autocomplete), the DHTML Style Guide states:

> "Tab moves focus into the edit field (Edit field to hold value of selected item in the dropdown list). A second Tab key selects the current item on the list, updates the edit field, closes the dropdown list, and moves focus to the next focusable item in the tab order."

If you're looking for consistency, that is how Tab should behave. If an item is selected in a dropdown (combo or autocomplete), that selection should be entered into the field and focus is set to the next item in the page tab order. If Tab were to keep focus in the same field, then the functionality of the Enter key is duplicated. With no other method to "select and move", the benefit of quickly filling out forms is diminished."

**Comment by samezyane** [comment]
Yeah, me also I have a request for select on tab and move to the next.

@gerwintown @granteagon did you find a workaround?
@anjmao from this thread you were convinced at some point and suddenly you changed your mind, is it really because you realized it is not a common behaviour?
I can see from googling results, people are forking code to add this!

**Comment by granteagon** [comment]
@samezyane I recommend you find a simpler implementation that this project, or write one yourself.  You can check out my fork but it's old, and it's only going to get older.  It might help you in the short term, however.  Best of luck.

**Comment by samezyane** [comment]
@granteagon Thank you for your advice.
