### ISSUE TITLE
Add new Tag on top

### ISSUE THREAD

**Issue by angelo510** [ng-select/ng-select#377]
### I need to make the Add New Tag button on Top
Currently when we have many options, I can't see the button at first even I don't have that item in the dropdown list.

![image](https://user-images.githubusercontent.com/23502859/37722641-e97e5010-2d02-11e8-80bb-bb1a47a8f667.png)

So if there's option to show "Add a new tag" button on top of the menu list that would be better to understand that if the item is exists or not.

Something like this one:
```
<ng-select
    [items]="items"
    [addTag]="true"
    [addButtonPosition]="top" // or "bottom" or "auto" same as [dropdownPosition]
    bindLabel="name"
    (add)="onAddItem($event)"
    [(ngModel)]="item">
</ng-select>
```
Cheers!

**Comment by varnastadeus** [comment]
@angelo510 in your case maybe you should filter items differently? Reason for it to be at the bottom is because user shouldn't be interested in adding new option when there are plenty of items to choose from.

**Comment by angelo510** [comment]
@varnastadeus I think this can be fixed easily in your side and its good to have an option to show buttons on top, even they could choose other items listed below.

**Comment by RobDaPraia** [comment]
> @angelo510 in your case maybe you should filter items differently?
> It is placed at the bottom because users shouldn't be interested in adding new options while there are plenty of items to choose from.

It all depends on your use case.

For our users it is also annoying that the "add item" tag is at the bottom. Would be much better if we could choose to set it at the top

"Plenty of items" In our case some of the items are in a table, some are in the cache, some coming from third parties, some are on the internet and we can have thousands of items, for example "Vessel names"

While we can show the items from the table/cache, the expensive calls we only make with the "add item" if not found in table/cache, but now you often have to scroll to the end, or start typing to make the list shorter and then use the "add item". It is not very intuitive for our users

Maybe you could improve it with filtering, but often I know the search it is not in the table/cache and I want to add the "add item" right away, but cannot without first scrolling to the end of the list, which gets annoying 

Since this item is closed, anyone found another solution to place the "add item" at the top?

**Comment by AsjadMahmood** [comment]
Any update on "Add new tag" on top

**Comment by Fdom92** [comment]
Just found this ticket, would be nice to have the option to move the ''Create new ...'' on top of the dropdown as another option for customize. For our use case is important to have this option based on client request.

**Comment by LunaSquee** [comment]
Interested in this as well

**Comment by LunaSquee** [comment]
I have applied a workaround using the search event by placing the search term into the start of the items array. It's not as pretty but it works good enough.

**Comment by namptx2019** [comment]
> I have applied a workaround using the search event by placing the search term into the start of the items array. It's not as pretty but it works good enough in my specific use case.

Can you show me your workaround? I still find the way to solve this issue in my project.

**Comment by roma2341** [comment]
> 
I am using ng-select in my own selection and have just added an 'addTagOnEnter' parameter that changes the behavior of pressing the Enter key. When the user does not see "Add Item", he can simply press Enter and the item will be added as is (not the first in the list). You can override "handleKeyCode" method to apply this behaviour and check keycode. I know this approach is not ideal, but maybe someone needs it as well as I do.
```
 ngAfterViewInit(): void {
        /*Replace key handler to avoid limitations*/
        let originalKeyCodeHandler = this.selectComponent.handleKeyCode;
        this.selectComponent.handleKeyCode = ($event:KeyboardEvent) => {
            if(this.addTagOnEnter && ($event.which == NgSelectKeyCode.Enter)) {
                if(typeof this.selectComponent.addTag == 'function') {
                    //let tag = this.selectComponent.addTag(this.selectComponent.searchTerm);
                    this.selectComponent.selectTag();
                    return;
                }
            }
            originalKeyCodeHandler.call(this.selectComponent,$event);
        }
    }
```

**Comment by roma2341** [comment]
> > I have applied a workaround using the search event by placing the search term into the start of the items array. It's not as pretty but it works good enough in my specific use case.
> 
> Can you show me your workaround? I still find the way to solve this issue in my project.
I am using ng-select in my own selection and have just added an 'addTagOnEnter' parameter that changes the behavior of pressing the Enter key. When the user does not see "Add Item", he can simply press Enter and the item will be added as is (not the first in the list). You can override "handleKeyCode" method to apply this behaviour and check keycode. I know this approach is not ideal, but maybe someone needs it as well as I do.
```
 ngAfterViewInit(): void {
        /*Replace key handler to avoid limitations*/
        let originalKeyCodeHandler = this.selectComponent.handleKeyCode;
        this.selectComponent.handleKeyCode = ($event:KeyboardEvent) => {
            if(this.addTagOnEnter && ($event.which == NgSelectKeyCode.Enter)) {
                if(typeof this.selectComponent.addTag == 'function') {
                    //let tag = this.selectComponent.addTag(this.selectComponent.searchTerm);
                    this.selectComponent.selectTag();
                    return;
                }
            }
            originalKeyCodeHandler.call(this.selectComponent,$event);
        }
    }
```

**Comment by kut** [comment]
You can also change the order of the "new tag button" via CSS:

```
.ng-dropdown-panel-items > div {
  display: flex;
  flex-direction: column;

  [role="option"]:not([id]) {
    order: -1;
  }
}
```

**Comment by scolacurcio** [comment]
+1 for adding this functionality!

A common use case where this would be necessary is when using <ng-select> as a search input that is fetching some auto-suggested options from a server. It's important for this use case to have the user's search term on top since hitting Enter automatically selects the first item in the list, in my case, the first auto-suggested result, which is not intuitive for the user.

Ideally, the first result would be "Search for {searchTerm}", followed by the list of suggestions, so that they can use the input as a regular search bar, where hitting Enter triggers a callback with the exact term they typed in.

**Comment by JanesH64** [comment]
Any updates on this issue? Would really appreciate this feature to be added. My users have the option to add userspecific tags until their searchterm is matched.

**Comment by kut** [comment]
We fixed this just by moving the item to the top by adding a couple of lines of CSS, without needing to change the ng-select library. See below. 

> You can also change the order of the "new tag button" via CSS:
> 
> 
> 
> ```
> 
> .ng-dropdown-panel-items > div {
> 
>   display: flex;
> 
>   flex-direction: column;
> 
> 
> 
>   [role="option"]:not([id]) {
> 
>     order: -1;
> 
>   }
> 
> }
> 
> ```
