### ISSUE TITLE
change input type

### ISSUE THREAD

**Issue by danitag78** [ng-select/ng-select#440]
I would like to use ng-select for all my input with type-ahead feature, but to do this I need to change also the input type (text|search|number|email|url) to use the keyboard features on mobile devices.

using this

`<ng-select [items]="faqFiltered"
    bindLabel="selFAQ"
    [searchFn]="customSearchFAQ"
    [(ngModel)]="selectedFAQ">`

current output is:

`<div class="ng-input"><input autocomplete="off" role="combobox" type="text"></div>`

and I would like (for example):

`<div class="ng-input"><input autocomplete="off" role="combobox" type="search"></div>`

**Comment by danitag78** [comment]
[http://mobileinputtypes.com/
](url)
or [https://aiocollective.com/field-types-in-forms-and-the-phone-keyboard/](url)

I create a page [http://vetreria.mosaicweb.it/input.html](url) to test different input type with a smartphone.

![input_email](https://user-images.githubusercontent.com/8328444/38625830-9bce18c8-3dab-11e8-8760-6e907070bd41.png)
![input_number](https://user-images.githubusercontent.com/8328444/38625831-9bead788-3dab-11e8-80b0-9e164c4b7fb8.png)
![input_search](https://user-images.githubusercontent.com/8328444/38625832-9c01f558-3dab-11e8-99a2-c3b928331855.png)
![input_text](https://user-images.githubusercontent.com/8328444/38625833-9c20feb2-3dab-11e8-8f48-08d9662d20b5.png)
![input_url](https://user-images.githubusercontent.com/8328444/38625835-9c4b23ea-3dab-11e8-8f94-b11f3fa757a4.png)

**Comment by rmcsharry** [comment]
In these screenshots the text and search keyboards are almost identical (but notice the magnifying glass bottom right for the search input, which is not shown for text input).

So basically the problem is not one of styling - on mobile the type of the input results in different keyboards being displayed. 

Hence setting the type correctly effects behaviour, not style. Therefore it's useful for consistent UX.
