### ISSUE TITLE
UX problem color

### ISSUE THREAD

**Issue by GoNode5** [ng-select/ng-select#45]
Very nice component.

![select1problem](https://user-images.githubusercontent.com/2210672/30972277-6271550c-a46a-11e7-957f-dc98b4a7004c.gif)

The first selection staying highlighted this is also confusing...
Besides color could/would it possible to to put an Icon  'tick' for the one(s) selected as extra?

**Comment by anjmao** [comment]
Thanks for reporting. This is known issue and should be fixed soon :) For putting you custom item you can use custom option template. See example https://github.com/ng-select/ng-select#custom-display-and-option-templates

**Comment by varnastadeus** [comment]
@GoNode5 custom templates are supported only for single select for now, if that is what you are asking.

**Comment by anjmao** [comment]
@varnastadeus Option custom templates are supported for both single and multiselect. Label templates are supported only in single select because it is much more complex. Probably we need to document this.

**Comment by GoNode5** [comment]
thnx for all your comments. I'am now using Chosen (jquery plugin), but would like to use native Angular.  With Chosen, selected items are grey. Although possible I almost never have to need or I filter disabled options that can't be selected anyway. Or show strikethrough? or make it CSS optional for all 3 options...

**Comment by varnastadeus** [comment]
@GoNode5 Regarding colors, current style is provided as baseline and since we can't match everyone's preference we will keep it that way, although there might be some slight changes in the future. If you want, you can customize it yourself e.g.

```css
ng-select .as-option.selected {
    background-color: red!important;
}
```

I added pull request #49 which fixes issue you mentioned ```The first selection staying highlighted...```. As to other features, please feel free to create new issue and we will consider implementing it.
