### ISSUE TITLE
Do we need to unsubscribe on component destroy?

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#455]
Currently I am using the `typeahead` as following and not `unsubscribing` from the feed on component destroy. Just wondering if we need to `unsubscribe`

```
this.tagsTypeahead
            .distinctUntilChanged()
            .debounceTime(400)
            .subscribe(term => this.loadFilteredTags(term));
```

**Comment by anjmao** [comment]
Hi @shyamal890, that is a good question. In current implementation you need to manage subscription by yourself because you are creating Observable and passing it to ng-select using [typeahead] input and then ng-select can emit filter term to your Observable. It is possible to implement this logic inside ng-select by one line of code, but I will check if that would be correct from user point of view.

```ts
// inside ng-select
ngOnDestroy() {
   this.typeahead.complete();
}
```

**Comment by shyamal890** [comment]
@anjmao it would be great if it can be handled inside ng-select.

**Comment by anjmao** [comment]
@varnastadeus Very good point.
@shyamal890  You can read this post which has good suggestion how to unsubscribe and cleanup all observables https://stackoverflow.com/questions/38008334/angular-rxjs-when-should-i-unsubscribe-from-subscription
