### ISSUE TITLE
Feature request: support for tree structure

### ISSUE THREAD

**Issue by k3nsei** [ng-select/ng-select#553]
### Expected behaviour
Support for nested options groups (tree like).
Something like:
- https://leovo2708.github.io/ngx-treeview/#/components
- https://valor-software.com/ng2-tree/index.html
- https://material.angular.io/components/tree/examples

With support for filtering, sorting and virtual scroll.

### Actual behaviour
There is only support for simple one level groups

### More Info
ng-select version: any

browser: any

**Comment by varnastadeus** [comment]
@k3nsei why not just use material tree component? This component is based on select element and I don't think this functionality has something in common with it.

**Comment by k3nsei** [comment]
@varnastadeus to not introduce additional dependencies.

**Comment by varnastadeus** [comment]
As I mentioned before, this component mimics select control and we are not planning to add any unrelated or uncommon features on top of it.

**Comment by k3nsei** [comment]
But it's multiselect but with more advanced behaviour.

**Comment by varnastadeus** [comment]
I would say it is completely different behavior and it should be a separate control. To keep our code base maintainable and small we are not considering features that are not useful for general user or are uncommon for select like control.

**Comment by jziggas** [comment]
I was looking for this feature as well. The use case is a multiselect control that has hierarchal nodes that can be asynchronously loaded as you expand them. As well as typeahead to filter upon the tree. It is not unrelated because it is still a multiselect control but I understand your need to limit the scope of your features - too bad. Thank you for the library regardless!

**Comment by gustavomick** [comment]
@varnastadeus I think when devs/biz request this tree feature is asking to have a similar feature to groupBy feature but with multiple levels instead of just one, if that correct, could you elaborate on why one-level is viable but multi-levels are not?, I think with your insights we can understand and communicate better why this is not the same / out of scope. thanks!

https://ng-select.github.io/ng-select#/grouping
