### ISSUE TITLE
Demo example where typeahead and virtualScroll (scrollToEnd) works together

### ISSUE THREAD

**Issue by Ratikant01** [ng-select/ng-select#615]
First of all thanks for this great project! We are actually trying to implement typeahead with virtualScroll (scrollToEnd) using this, but facing issues to make it work together, so it would be really great if you can create a demo example! Thanks in advance!

**Comment by varnastadeus** [comment]
Hi, can you create example using [stackblitz](http://stackblitz.com/) ? Then I could take a look what you are doing wrong

**Comment by Ratikant01** [comment]
Thanks, I have created one: [here](https://stackblitz.com/edit/angular-bpxphk). I am currently using Angular 5 and ng-select 1.5.2. But this stackblitz has Angular 6 - so not sure how to change that.. but all the code is available there.

What I need is:

1) Should show 10 records by default (on open of drop-down / even before user types anything)
2) User can scroll to end to fetch again 10 records, and till end of records
3) User can search (typeahead) and it should return 10 records from server as per matching term and now if he scrolls the next setup matching records should be fetched from server.

Issue: Scroll functionality not working when adding typeahead.. without typeahead scroll is working fine.

**Comment by varnastadeus** [comment]
https://stackblitz.com/edit/ng-select-infinite. 
Here is the example. I made my own since yours didn't worked.

**Comment by Ratikant01** [comment]
It was a great help!! Thanks a lot!

**Comment by dixitshantanu-106** [comment]
@varnastadeus 

I have same use case as you have implemented here https://stackblitz.com/edit/ng-select-infinite.
Only I have used [(ngModel)] to bind the current selected value when user opens a saved form, in my case due to ngmodel when user scrolls down and new items are added to the list, in the UI only the current selected item exists in the list and nothing else, can you please add ngmodel to your example and make it work, thanks.
