### ISSUE TITLE
Selectable group not initialized properly

### ISSUE THREAD

**Issue by asleire** [ng-select/ng-select#658]
### Issues
There are a few related issues with selectable groups:

1.  When you set the value to an array containing the group name you would expect the group to be selected, but it is not (you can select the group again, duplicating the value)
2. When you set the value to an array containing the group name, and the `bindLabel` and `bindValue` input target different properties, the input field will display an empty tag
3. A consequence of this is that when you set the value equal to the control value (e.g. `ctrl.setValue(ctrl.value)`) the groups will not be selected and the groups will possibly display as empty values
### Reproduction
See https://stackblitz.com/edit/ng-select-pnmeum for an example.

1. Click 'Set Argentina' to set the value to ['Argentina']. One would expect the group 'Argentina' to be selected, but it is not
2. Click 'Set Argentina' to set the value to ['Argentina']. In the bottom select-component an empty label is shown instead of 'Argentina'
3. With any group selected, click 'Set current value'. Currently selected groups will be unselected even though the value stays the same

### More Info
ng-select version: 2.3.1

browser: Chrome

**Comment by vaibhav4465** [comment]
@varnastadeus : I am also facing same issue, while trying to provide values to ngModel associated with the ng-select. 
I am using ng-select for a production application. Unfortunately, I do not have the bandwidth nor apt know how to fix it myself in a fork of ng-select repo.

I see that you assigned this issue to yourself, do we have any update on this issue?

**Comment by varnastadeus** [comment]
Current status is that I am not sure if this should work with given setup, since there is no way to resolve value by given model. I wrote short [explanation](https://github.com/ng-select/ng-select/issues/666#issuecomment-412282503) how values are resolved and solution here is to use `compareWith`.

Here is working [example](https://stackblitz.com/edit/ng-select-pjeyj4). I will keep this issue to check if there can be done something on `ng-select` side.
