### ISSUE TITLE
BUG: Model changed after ngModel is updated

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#666]
Please fill below information if issuing a bug report. 
### Expected behaviour
When a ngModel reference object is changed that change should be immediately updated in `ng-select` and carry forward

### Actual behaviour
https://stackblitz.com/edit/ng-select-y3vh4c?file=app/app.component.ts
- Select Vilinius city. 
- Now press `Change` button. The Vilinius object is updated with `Id` change
- Now add one more tag, you would see Vilinius object go back to old `Id` which shouldn't happen.

### More Info
ng-select version: 2.3.2

browser: Chrome

reproducible in demo page: [YES]

**Comment by varnastadeus** [comment]
I don't think it is a bug. When you assign value to your model, here whats happening under the hood:

1. if `compareWith` is defined, ng-select tries to resolve item using your compare fn
2. if `bindValue` is defined, ng-select tries to resolve item comparing exact properties
3. if neither are defined, ng-select tries to resolve item comparing model with items, for objects reference should match.
4. if there is no match, lastly it tries to resolve item using `bindLabel`

In your case it finds item by label and sets it as selected (internally with id 0), then when you select another item it just updates your `ngModel` with selected values. Try adding `compareWith` to see 
that `Vilnius` won't get selected since ids don't match.

```javascript
    compareFn = (a, b) => a.id === b.id;
```
