### ISSUE TITLE
select by default a parent group doesn't work

### ISSUE THREAD

**Issue by yduartep** [ng-select/ng-select#875]
**Describe the bug**
I have an ng-select grouped by a specific property that is also selectable. I would like to pre-fill the ng-select with a parent group and another child value but I always receive the following error and the selection is not displayed:

Binding object({"group":"Developers"}) with bindValue is not allowed.

**To Reproduce**
- Go to https://stackblitz.com/edit/ng-select-ejmvk8
- The ngModel *values* is initialized with: values = [{group: 'Developers'}, 3];
- When the component finishes the loading process, no value is selected in the ng-select but should appears two tags selected Developers and Marketing.

**Expected behavior**
When the component has been already initialized the Developers and Marketing tags should be selected and no child department belong to Developers should be displayed but no selection is done and in console you could see the warning error: Binding object({"group":"Developers"}) with bindValue is not allowed.

**Screenshots**
![ng select - default values](https://user-images.githubusercontent.com/24477117/47015373-103e3780-d14d-11e8-8c30-be85fda78427.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra version 10.13.6
 - Browser [chrome]
 - Version [69.0.3497.100 (Official Build) (64-bit)]

**Comment by varnastadeus** [comment]
Here e30e365cf430b1efc9475c86001b7a74bfec384e  I added change which will allow to have mixed selected model like in your example, but to make your example work you still need to use `compareWith` since there is no way to resolve options based on your model. 

here is working example with latest version, https://stackblitz.com/edit/ng-select-svhyjc?file=app/app.component.ts
