### ISSUE TITLE
On 1st time open, can't see option selected if it's at the bottom of the list

### ISSUE THREAD

**Issue by caribou71** [ng-select/ng-select#899]
**Describe the bug**
On 1st time open, can't see the option selected if it's at the bottom of the list..we see only the first 4-6 at the beginning..if we scroll down we can see it is selected...but the focus didn't go there on the 1st click

**To Reproduce**
https://stackblitz.com/edit/ng-select-m7acas?file=app/app.component.ts

**Expected behavior**
can't see the option selected when we open the 1st time...it is working if you close it and re-open it..only the 1st time it doesn't work

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 69.0.3497.100

**Comment by BruneXX** [comment]
Hi Guys, there's no update here?

**Comment by BruneXX** [comment]
Hi @caribou71 Have you managed to fix that? any though on this? will be appreciated. Thanks!

**Comment by BruneXX** [comment]
Hi @varnastadeus 

Thanks to follow into this, do you have an estimated date with a fix? I just want to know in order to see if I need to take a look over another solution regarding this issue, please, also if you know the part of the component code this is originated, will be very helpful for me to apply a temporary patch, until the ng-select team or you relase a new version with the fix.

Thank you so much!

Best regards,

**Comment by eladglobalbit** [comment]
@varnastadeus  What is expected time to fix this problem

**Comment by Badazdz** [comment]
Hi, I have found a workaround for this issue.
1. Add ID to you ng-select tag and define method for open event:
```html
<ng-select #ngSelect [items]="items" [(ngModel)]="selectedItemId" (open)="focusSelectedItem()"></ng-select>
```
2. Link component to your code:
```typescript
@ViewChild('ngSelect') ngSelect: NgSelectComponent;
```
3. Method defined for open event:
```typescript
focusSelectedItem(): void {

    if (this.ngSelect.selectedItems == null || this.ngSelect.selectedItems.length == 0) {
        return;
    }

    setTimeout(() => {
        if (isNullOrUndefined(this.ngSelect.dropdownPanel)) {
            this.focusSelectedItem();
        } else {
            this.ngSelect.dropdownPanel.scrollInto(this.ngSelect.selectedItems[0]);
        }
    }, 10);
}
```

**Comment by eladglobalbit** [comment]
@bioub @varnastadeus  This does not work yet? I tried the solution of @bioub  but this not works.

**Comment by Klemensas** [comment]
Any progress on this issue, do you need any help?

**Comment by varnastadeus** [comment]
I haven't had much time to take a deeper look into it, but contributions are always welcome

**Comment by baveryt** [comment]
I'm not able to work on doing the fix for it..but I do know what the issue is. The problem is within the scrollInto logic. It is trying to determine the height of children to see how far down in the list to scroll to, however the dropdown has not yet been rendered so all the children have a height of 0 on them and thus the scroll top gets calculated to 0. The reason the timeout works from the suggestion from @Badazdz is simply because the render has completed and the children have the proper heights associated and the scroll top gets calculated properly. Hope that helps point someone to where the issue is if they wish to work on a contribution to fix it. For the time being we have implemented the solution from @Badazdz

**Comment by Richard-biz** [comment]
Hi There i did like this it working properly. due to NAN in Math.min value for the index the scroll top set in 0 so the issue is came.
 setTimeout(() =>{
                const contentEl: HTMLElement = this.contentElementRef.nativeElement;
                const childrenHeight = Array.from(contentEl.children).slice(0, index).reduce((c, n) => c + n.clientHeight, 0);
                if(isNaN(Math.min(index, buffer))){
                    scrollEl.scrollTop = childrenHeight;
                }else{
                    scrollEl.scrollTop = childrenHeight - (d.childHeight * Math.min(index, buffer));
                }
            });
if anything better than this let me know, Thanks
