### ISSUE TITLE
Clear 'x' icon missing when using ng-template for selected items

### ISSUE THREAD

**Issue by dannygoncalves** [ng-select/ng-select#990]
**Describe the bug**
When using ng-template for the selected items. the 'x' icon to remove the element is missing, there is not enough documentation when using the ng-template so I'm not sure if I'm missing anything but it seems like a bug to me.

**Reproducible example**
[Stackblitz](https://stackblitz.com/edit/angular-ng-select-issue?file=src%2Fapp%2Fapp.component.html) 

**Expected behavior**
'x' icon should be visible per selected item.

**Comment by dannygoncalves** [comment]
I had to add the icon to the ng-template, so this is not an actual bug, just a bad implementation on my side.
I'll close this, my apologies.

**Comment by HammNCheez** [comment]
For anyone wondering how to implement this yourself. Just add a span with the X in it with a click listener that calls a method in your component that will remove the selected item from your model, see the snippet below. The `item` object that it adds on the call will be the object that is selected. 

In Template:
`<span class="ng-value-icon left" (click)="unselect(item);" aria-hidden="true">×</span>`

In component:
```
unselect(item: any) {
    if (!item) { return;}
    this.selectedItems= _.filter(this.selectedItems, (i: any) => {
      return i.id !== item.id;
    });
  }
```

As a reminder this ngSelect does dirty checking for changes so you need to replace the `ngModel` array instead of just updating it in-place.
